//Taylor Zweigle, 2024
export const CITIES = [
  { value: "Addison", label: "Addison" },
  { value: "Allen", label: "Allen" },
  { value: "Anna", label: "Anna" },
  { value: "Aubrey", label: "Aubrey" },
  { value: "Carrollton", label: "Carrollton" },
  { value: "Colleyville", label: "Colleyville" },
  { value: "Coppell", label: "Coppell" },
  { value: "Dallas", label: "Dallas" },
  { value: "Fairview", label: "Fairview" },
  { value: "Flower Mound", label: "Flower Mound" },
  { value: "Fort Worth", label: "Fort Worth" },
  { value: "Frisco", label: "Frisco" },
  { value: "Garland", label: "Garland" },
  { value: "Grand Prairie", label: "Grand Prairie" },
  { value: "Grapevine", label: "Grapevine" },
  { value: "Irving", label: "Irving" },
  { value: "Lewisville", label: "Lewisville" },
  { value: "McKinney", label: "McKinney" },
  { value: "Plano", label: "Plano" },
  { value: "Prosper", label: "Prosper" },
  { value: "Richardson", label: "Richardson" },
  { value: "Rockwall", label: "Rockwall" },
  { value: "Southlake", label: "Southlake" },
  { value: "The Colony", label: "The Colony" },
  { value: "Weatherford", label: "Weatherford" },
];

export const TYPES = [
  { value: "American", label: "American" },
  { value: "Asian", label: "Asian" },
  { value: "Bagel", label: "Bagel" },
  { value: "Bar", label: "Bar" },
  { value: "BBQ", label: "BBQ" },
  { value: "Breakfast", label: "Breakfast" },
  { value: "Burger", label: "Burger" },
  { value: "Cajun", label: "Cajun" },
  { value: "Coffee", label: "Coffee" },
  { value: "Food Court", label: "Food Court" },
  { value: "Indian", label: "Indian" },
  { value: "Italian", label: "Italian" },
  { value: "Mexican", label: "Mexican" },
  { value: "Pizza", label: "Pizza" },
  { value: "Poke", label: "Poke" },
  { value: "Pub", label: "Pub" },
  { value: "Salad", label: "Salad" },
  { value: "Sandwhich", label: "Sandwhich" },
  { value: "Seafood", label: "Seafood" },
  { value: "Southwestern", label: "Southwestern" },
  { value: "Steakhouse", label: "Steakhouse" },
  { value: "Sushi", label: "Sushi" },
  { value: "Taco", label: "Taco" },
  { value: "Vietnamese", label: "Vietnamese" },
  { value: "Winery", label: "Winery" },
  { value: "Wings", label: "Wings" },
];

export const RATING = [
  { value: "0.5", label: "0.5" },
  { value: "1", label: "1" },
  { value: "1.5", label: "1.5" },
  { value: "2", label: "2" },
  { value: "2.5", label: "2.5" },
  { value: "3", label: "3" },
  { value: "3.5", label: "3.5" },
  { value: "4", label: "4" },
  { value: "4.5", label: "4.5" },
  { value: "5", label: "5" },
];

export const COST = [
  { value: "$", label: "$" },
  { value: "$$", label: "$$" },
  { value: "$$$", label: "$$$" },
  { value: "$$$$", label: "$$$$" },
];

export const VISITED = [
  { value: "No", label: "No" },
  { value: "Yes", label: "Yes" },
];
