//Taylor Zweigle, 2024
export const GET_RESTAURANTS = "GET_RESTAURANTS";
export const CREATE_RESTAURANT = "CREATE_RESTAURANT";
export const DELETE_RESTAURANT = "DELETE_RESTAURANT";

export const GET_SELECTED_THEME = "GET_SELECTED_THEME";
export const SET_SELECTED_THEME = "SET_SELECTED_THEME";

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
