//Taylor Zweigle, 2025
export const GET_RESTAURANTS = "GET_RESTAURANTS";
export const CREATE_RESTAURANT = "CREATE_RESTAURANT";
export const DELETE_RESTAURANT = "DELETE_RESTAURANT";

export const GET_LOCATIONS = "GET_LOCATIONS";
export const CREATE_LOCATION = "CREATE_LOCATION";
export const DELETE_LOCATION = "DELETE_LOCATION";

export const GET_FILTERS = "GET_FILTERS";
export const CREATE_FILTER = "CREATE_FILTER";
export const DELETE_FILTER = "DELETE_FILTER";
export const RESET_FILTERS = "RESET_FILTERS";

export const GET_LOCATION_CATEGORY = "GET_LOCATION_CATEGORY";
export const SET_LOCATION_CATEGORY = "SET_LOCATION_CATEGORY";

export const GET_THEME = "GET_THEME";
export const SET_THEME = "SET_THEME";

export const GET_CURRENT_LOCATION = "GET_CURRENT_LOCATION";
export const SET_CURRENT_LOCATION = "SET_CURRENT_LOCATION";

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
